import java.io.IOException;

public class TestProgram16 {
  public static void main(String[] args) {
    // try{
    //   System.out.println("try");
    //   int result = 1/0;
    //   throw new ClassNotFoundException("");
    // } catch (ClassNotFoundException e) {
    //   System.out.println("catch 1");
    //   throw new RuntimeException("Exception");
    // } catch (ArithmeticException e) {
    //   System.out.println("Arithmetic Exception");
    //   throw new IOException("");
    // } catch (IOException e) {
    //   System.out.println("IOException");
    // } catch (Exception e) {
    //   System.out.println("catch");
    // } finally {
    //   System.out.println("finally");
    // }
  }
}
